name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./envirment/prod

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Azure Login
        uses: azure/login@v2
        if: ${{ secrets.AZURE_CREDENTIALS != '' }}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          terraform init

      - name: Terraform Validate
        run: |
          echo "Validating Terraform Configuration..."
          terraform validate

      - name: Terraform Plan
        run: |
          echo "Running Terraform Plan..."
          terraform plan
